Closes #78
StableTechnologies/TEZEX pull request #84
Opened 2021-08-20 18:25 UTC by Aeesh

2021-08-23 02:59 UTC, anonymoussprocket commented on client/src/components/home/index.jsx
> +        .toFixed(2);
this should use token decimals, 6 (rather than the full 8) for BTC, 4 (rather than 18) for ETH. 0.0001BTC is 1.32XTZ right now

2021-08-23 03:00 UTC, anonymoussprocket commented on client/src/components/home/index.jsx
> +              {(minReceived <= 0) &&  "Minimum Receiveable must be greater than 0"}
-> "Minimum receivable must be greater than zero"

2021-08-23 03:01 UTC, anonymoussprocket commented on client/src/components/home/index.jsx
> +                              Please enter an amount lower than {" "} {Number(swapLimit)} {" "} {inputToken.title}
number cast isn't needed here

2021-08-23 14:53 UTC, anonymoussprocket approved these changes

2021-08-23 19:00 UTC, gdsoumya commented
The max swap check logic is incorrect please correct it as discussed.

2021-08-23 19:01 UTC, gdsoumya requested changes

2021-08-23 19:01 UTC, gdsoumya commented on client/src/components/home/index.jsx
> +    }
The max swap check logic is incorrect please correct it as discussed.

2021-08-23 19:02 UTC, gdsoumya commented on client/src/components/home/index.jsx
> +    }
Should be `if(Number(inoutAmount) > Number(swapLimit))`

2021-08-23 19:05 UTC, gdsoumya requested changes

2021-08-23 19:05 UTC, gdsoumya commented on client/src/components/home/index.jsx
> +    if(Number(minReceived) > Number(swapLimit)){
All numeric checks should be done in BigNumber format, check line 181

2021-08-24 17:54 UTC, navi-arneja approved these changes

2021-08-24 17:55 UTC, mayakruse approved these changes

2021-08-24 18:33 UTC, mayakruse approved these changes

2021-08-24 20:29 UTC, gdsoumya approved these changes

2021-08-24 20:29 UTC, merged